[project]
name = "pi-watering"
version = "0.1"
description = "Raspberry Pi script that will water my garden"
authors = [
    {name = "elastic-pangolin", email="invalid@example.com"},
]
dependencies = [
    "schedule>=1.2.0"
]
requires-python = ">=3.7"
